[versions]
# See https://maven.twelveiterations.com/service/rest/repository/browse/maven-public/net/blay09/mods/balm-common/
balm = "21.11.6"
minecraft = "1.21.11"
# See https://projects.neoforged.net/neoforged/neoform
neoForm = "1.21.11-20251209.172050"
# See https://projects.neoforged.net/neoforged/neoforge
neoForge = "21.11.38-beta"
# See https://files.minecraftforge.net
forge = "61.1.0"
# See https://fabricmc.net/develop/
fabricApi = "0.141.3+1.21.11"
fabricLoader = "0.18.4"
kuma = "21.11.12"
geckolib = "5.4.3"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
# Parchment adds human-readable names to parameters. You can find the latest version at: https://parchmentmc.org/docs/getting-started
parchment = { module = "org.parchmentmc.data:parchment-1.21.10", version = "2025.10.12" }

balmCommon = { module = "net.blay09.mods:balm-common", version.ref = "balm" }
balmNeoForge = { module = "net.blay09.mods:balm-neoforge", version.ref = "balm" }
balmForge = { module = "net.blay09.mods:balm-forge", version.ref = "balm" }
balmFabric = { module = "net.blay09.mods:balm-fabric", version.ref = "balm" }

kumaCommon = { module = "net.blay09.mods:kuma-api-common", version.ref = "kuma" }
kumaNeoForge = { module = "net.blay09.mods:kuma-api-neoforge", version.ref = "kuma" }
kumaForge = { module = "net.blay09.mods:kuma-api-forge", version.ref = "kuma" }
kumaFabric = { module = "net.blay09.mods:kuma-api-fabric", version.ref = "kuma" }

geckolibCommon = { module = "software.bernie.geckolib:geckolib-common-1.21.11", version.ref = "geckolib" }
geckolibNeoForge = { module = "software.bernie.geckolib:geckolib-neoforge-1.21.11", version.ref = "geckolib" }
geckolibForge = { module = "software.bernie.geckolib:geckolib-forge-1.21.11", version.ref = "geckolib" }
geckolibFabric = { module = "software.bernie.geckolib:geckolib-fabric-1.21.11", version.ref = "geckolib" }

neoForm = { module = "net.neoforged:neoform", version.ref = "neoForm" }
neoForge = { module = "net.neoforged:neoforge", version.ref = "neoForge" }
forge = { module = "net.minecraftforge:forge", version.ref = "forge" }
fabricApi = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricApi" }
fabricLoader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }

mixin = { module = "org.spongepowered:mixin", version = "0.8.7" }

[plugins]
fabricLoom = { id = "fabric-loom", version = "1.14-SNAPSHOT" }
modDevGradle = { id = "net.neoforged.moddev", version = "2.0.140" }
forgeGradle = { id = "net.minecraftforge.gradle", version = "[7,8)" }
curseForgeGradle = { id = "net.darkhax.curseforgegradle", version = "1.1.26" }
modrinthMinotaur = { id = "com.modrinth.minotaur", version = "2.+" }
